# set colors
set -g default-terminal "tmux-256color"

# use zsh
set-option -g default-shell /bin/zsh

# change split screen from % and " to - and |
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config with prefix r
bind r source-file ~/.tmux.conf

# switch panes with meta key
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# switch panes with meta key... vim navigation
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# configure catppuccin theme
set -g @catppuccin_flavor "frappe"
set -g @catppuccin_window_status_style "rounded"

# load Catppuccin theme for tmux
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# modify the status line
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux
