format = """
$os\
$username$hostname\
[║](bg:blue fg:pink2)\
$directory\
[║](bg:blue fg:pink2)\
$git_branch\
$git_status\
$git_metrics\
[║](fg:pink2 bg:blue)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nim\
$nodejs\
$php\
$rust\
$scala\
[║](fg:pink2 bg:blue)\
$docker_context\
[║](fg:blue)\
\n$character"""

add_newline = false

palette = "synthwave_circuit"

# https://www.media.io/color-palette/cyberpunk-color-palette.html
[palettes.synthwave_circuit]
blue = "#120A3A"
blue2 = "#0b1026"
pink = "#FF3B7F"
pink2 = "#ff2e63"
cyan = "#00F5D4"
cyan2 = "#08d9d6"
yellow = "#FFD166"
yellow2 = "#f9ed69"
purple = "#2D1B69"
purple2 = "#252A41"
green = "#87ff00"
black = "#0c0f0a"

[os]
disabled = false
style = "bold fg:cyan bg:blue"
format = "[ $symbol]($style)"

[os.symbols]
AIX = "➿ "
Alpaquita = "🔔 "
AlmaLinux = " "        # nf-linux-almalinux
Alpine = " "           # nf-linux-alpine
Amazon = " "
Android = " "          # nf-fa-android
Arch = " "             # nf-linux-archlinux
Artix = " "            # nf-linux-artix
#Bluefin = "🐟 "
CachyOS = "🎗️ "
CentOS = " "           # nf-linux-centos
Debian = " "           # nf-linux-debian
DragonFly = "🐉 "
Emscripten = "🔗 "
EndeavourOS = " "      # nf-linux-endeavour
Fedora = " "           # nf-linux-fedora
FreeBSD = " "          # nf-linux-freebsd
Garuda = " "           # nf-linux-garuda
Gentoo = " "           # nf-linux-gentoo
HardenedBSD = "🛡️ "
Illumos = " "          # nf-linux-illumos
Kali = " "             # nf-linux-kali_linux
Linux = " "            # nf-linux-tux
Mabox = "📦 "
Macos = " "            # nf-linux-apple
Manjaro = " "          # nf-linux-manjaro
Mariner = "🌊 "
MidnightBSD = "🌘 "
Mint = " "             # nf-linux-linuxmint
NetBSD = "🚩 "
NixOS = " "            # nf-linux-nixos
Nobara = " "           # nf-linux-nobara
OpenBSD = " "          # nf-linux-openbsd
OpenCloudOS = "☁️ "
openEuler = "🦉 "
openSUSE = " "         # nf-linux-opensuse
OracleLinux = " "      # nf-dev-oracle
Pop = " "              # nf-linux-pop_os
Raspbian = " "         # nf-linux-raspberry_pi
Redhat = " "           # nf-linux-redhat
RedHatEnterprise = " " # nf-linux-redhat
RockyLinux = " "       # nf-linux-rocky_linux
Redox = "🧪 "
Solus = " "            # nf-linux-solus
SUSE = " "             # nf-fa-suse
Ubuntu = " "           # nf-linux-ubuntu
Ultramarine = "🔷 "
Unknown = "❓ "
Uos = "🐲 "
Void = " "             # nf-linux-void
Windows = " "          # nf-custom-windows

[username]
disabled = false
show_always = false
style_root = "bold bg:bright-red fg:black"
style_user = "bold bg:blue fg:yellow2"
format = "[$user]($style)[ in ](bg:blue fg:cyan)"

[hostname]
disabled = false
ssh_only = true
ssh_symbol = "🌐"
trim_at = "."
style = "bold bg:blue fg:yellow"
format = "[$ssh_symbol$hostname ]($style)"

[directory]
style = "bold bg:blue fg:cyan"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰎆 "
"Pictures" = " "
"Code" = " "
"code" = " "

[git_branch]
symbol = "󰘬"
style = "bold bg:blue fg:cyan"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold bg:blue fg:yellow"
format = '[($all_status$ahead_behind )]($style)'

[git_metrics]
added_style = "bold bg:blue fg:green"
deleted_style = "bold bg:blue fg:bright-red"
disabled = false
format = "([+$added]($added_style))([-$deleted]($deleted_style))[ ](bg:blue)"

[c]
symbol = "C"
style = "bold bg:blue fg:bright-red"
version_format = "v${major}.${minor}"
format = '[ $symbol ($version)]($style)'

[cmake]
symbol = " "
style = "bold bright-red bg:yellow"
version_format = "v${major}.${minor}"
format = '[ $symbol ($version)]($style)'

[cobol]
style = "bold bright-red bg:yellow"
version_format = "v${major}.${minor}"
format = '[ $symbol ($version)]($style)'

[nodejs]
symbol = ""
style = "bold bright-red bg:yellow"
version_format = "v${major}.${minor}"
format = '[ $symbol ($version)]($style)'

[rust]
symbol = "🦀" # I know there's an official logo, but the crab is cute.
version_format = "v${major}.${minor}"
format = '[ $symbol](bold fg:bright-red bg:blue)[($version) ](bg:blue fg:cyan)'

[golang]
symbol = ""
style = "bold bright-red bg:yellow"
version_format = "v${major}.${minor}"
format = '[ $symbol ($version)]($style)'

[php]
symbol = "󰌟 "
style = "bold bright-red bg:yellow"
version_format = "v${major}.${minor}"
format = '[ $symbol ($version)]($style)'

[docker_context]
symbol = " "
style = "bold bg:blue fg:cyan2"
format = "[via ](bg:blue fg:cyan2)[$symbol$context ]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bold bg:yellow fg:blue"
format = '[ 󰥔 $time ]($style)'
